---
- name: Install Estafet Microservices Application in Openshift
  hosts: all
  vars_files:
    - create-local-environment-vars.yml
    - microservices-vars.yml
  tasks:
    - include: initial-setup.yml
    - include: environment-setup.yml
    - include: jaeger-setup.yml
    - include: microservices-setup.yml
