---
- name: Define Openshift project
  shell: "oc project {{ project }}"
  tags:
    - openshift

- include: amq-vars.yml

- name: Create the database depending on whether environment is aws
  include_tasks: "create-db.yml"
  when: "not {{ external_db }}"
  tags:
    - db
    - postgresql

- name: Create the external database service 
  shell: "oc create -f external-postgres-service.yml"
  when: "{{ external_db }}"
  tags:
    - db
    - postgresql

- name: Create the external database endpoint 
  shell: "oc create -f external-postgres-endpoint.yml"
  when: "{{ external_db }}"
  tags:
    - db
    - postgresql

- name: Create the db based microservices applications using the source to image builder
  include_tasks: "create-app-with-db.yml"
  vars:
    repo: "{{ item.repo }}"
    microservice: "{{ item.name }}"
  when: "{{ item.db }}"
  with_items: "{{ microservices_scrum_projects }}"
  tags:
    - openshift

- name: Create the non db based microservices applications using the source to image builder
  include_tasks: "create-app-without-db.yml"
  vars:
    repo: "{{ item.repo }}"
    microservice: "{{ item.name }}"
  when: "not {{ item.db }}"
  with_items: "{{ microservices_scrum_projects }}"
  tags:
    - openshift
